### ISSUE TITLE
Prepayment

### ISSUE THREAD

**Issue by DonnaWB** [Acumatica/PrintCustomerRefundPkg#1]
How can we get this to work for refunding a prepayment?  It looks like it only works on a credit memo?

**Comment by dgodsill** [comment]
Anyone know if this works on 2018R2?  I have a customer with this version.

**Comment by DhirenChhapgar** [comment]
@DonnaWB  - Yes, it works only with Credit Memo.

@dgodsill - Yes, Customization works with 2018R2 and 2019R1.

**Comment by dgodsill** [comment]
Thanks. Please update the git hub page.
Dennis W. Godsill
Principal Consultant
Office: 860.833.8325 | Mobile: 860.833.8325  | E-mail: dgodsill@jaas.net<mailto:dgodsill@jaas.net>
