### ISSUE TITLE
Customer wants to use the same numbering sequence as AP checks.  Is this possible.

### ISSUE THREAD

**Issue by dgodsill** [Acumatica/PrintCustomerRefundPkg#2]
Also format to use is check with remittance not just check since almost everyone prints some combination of check-stub-stub (sequence may vary) since most checks are printed on 8x11 check stock.

**Comment by sfendt11** [comment]
I've been looking at this customization and after testing I have the same issue. I'm pretty sure, after a quick test, you can go into the customization under CODE, ARPaymentEntryExt, and replace the ARLastRefNbr fields to use APLastRefNbr. This pulls the last AP number into the reference field and sets the next AP # on the payment method profile.  Next I tested on the AP side and it did go to the next # after the customer refund #.

I'm not a programmer and I haven't spent much time on verifying but seems like this worked great so far on 2 customer refund tests.

**Comment by DhirenChhapgar** [comment]
@dgodsill 
#1 Yes, AP numbering sequence can be used.
#2 Custom report AR640501.rpx can be further modified to achieve desired format of the refund check.
