### ISSUE TITLE
Unable to print checks for customer payments that do not have a invoice

### ISSUE THREAD

**Issue by busyfritz** [Acumatica/PrintCustomerRefundPkg#4]
Can the table relations in the check printing "report" be adjusted to not require any kind of receivables document please? Prepayments and "Unknown" payments do not have a receivables document typically.
Ref #1

**Comment by shawnburt** [comment]
> Can the table relations be adjusted to not require any kind of receivables document please? Prepayments and "Unknown" payments do not have a receivables document typically.
> Ref #1

@busyfritz  in the case of Prepayments wouldn't you just create a CreditMemo to represent the desire to refund the prepayment then attach that AR Doc to the refund? Really that should work for any kind of payment.

**Comment by busyfritz** [comment]
That could work but then that leaves the customer with a negative balance right?

**Comment by shawnburt** [comment]
> That could work but then that leaves the customer with a negative balance right?

Testing that right now. Will let you know :)

**Comment by shawnburt** [comment]
> That could work but then that leaves the customer with a negative balance right?

![image](https://user-images.githubusercontent.com/3484399/73774951-c5797200-4739-11ea-9ed5-39d16fd129ec.png)
looks like the CM is not necessary you just point at the Prepayment as your AR Ref document in Documents To Apply.

FYI. I created and SO and applied a Prepayment and released it.
this creates an AR Payment record that you can reference in the Documents to Apply section of the Customer Refund.

**Comment by busyfritz** [comment]
> > That could work but then that leaves the customer with a negative balance right?
> 
> ![image](https://user-images.githubusercontent.com/3484399/73774951-c5797200-4739-11ea-9ed5-39d16fd129ec.png)
> looks like the CM is not necessary you just point at the Prepayment as your AR Ref document in Documents To Apply.
> 
> FYI. I created and SO and applied a Prepayment and released it.
> this creates an AR Payment record that you can reference in the Documents to Apply section of the Customer Refund.

Yes, that part works perfectly but because of how to check form relations are set up, the check won't print. The check "report" relations are setup to require a CM. It just prints blank if there is none. That's the issue.

**Comment by shawnburt** [comment]
ah, I see your issue then, sorry for being a bit slow :)
I will see if I can resolve that.

**Comment by busyfritz** [comment]
> ah, I see your issue then, sorry for being a bit slow :)
> I will see if I can resolve that.

Any success with this?

**Comment by DhirenChhapgar** [comment]
@busyfritz , at present Refund Check Report doesnt work with Pre-Payments.  Refund Check Report AR640501.rpx is included in this customization package as open source which you can alter as per your need.

**Comment by busyfritz** [comment]
Dhiren,
Shawn Burt(works for our Acumatica partner) is working on this issue. Please leave open

**Comment by megamorphg** [comment]
@busyfritz were you ever able to resolve this? I've been trying to edit the report and it looks like it will need to be heavily modified since it is using ARInvoice table (which is only affected by Credit Memos)

**Comment by busyfritz** [comment]
@megamorphg No I never got it resolved. We're still planning on doing that at some point though unless someone else beats us to it.

Agreed, it will be a very large rewrite but it's worth it. I'm surprised that this wasn't done out of the box.
